version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=sales_cart
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=Abrir.01
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
